### ISSUE TITLE
Bug in steepshot

### ISSUE THREAD

**Issue by pvrp2** [Chainers/steepshot-mobile#131]
#### Project info 
Name: Steepshot
Respiratory:https://github.com/Chainers/steepshot-mobile

#### Expected behavior
When the button post is pressed it should need to post my photo on steemit.
#### Actual behavior
When I tried to push post button it show error as  the below screenshot
#### Screenshot of bug
![Screenshot_20180529-203404.png](https://cdn.steemitimages.com/DQmSNm2qwMo3yFL9mY1dkdL2E4RmQXDjXHvBo4H1dhiY1RZ/Screenshot_20180529-203404.png)![Screenshot_20180529-202931.png](https://cdn.steemitimages.com/DQmaqAjCEXxbvcit5nLZN99HNmwadDX6H3MPuFwbCe3Qc5J/Screenshot_20180529-202931.png)![Screenshot_20180529-203428.png](https://cdn.steemitimages.com/DQmZZ8caW76p2GhXApTWugsR4qDVXU7DSeVjDHxsiRPC8RL/Screenshot_20180529-203428.png)

#### Step to reproduce
* Download Steepshot app from play store.
* Sign in with appropriate Id.
* Post a photo, then bug will start.
#### Device info
Device- Mi A1 Google phone
OS- 8.0 Oreo

**Comment by KorzunAV** [comment]
Hi, this standard message is displayed when the server is unavailable. The text of the message will be changed to more friendly
