### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by pvrp2** [Chainers/steepshot-mobile#160]
ame: Steepshot
Repository: https://github.com/Chainers/steepshot-mobile
Device: MI A1
Description: 
While trying to login in the to the steemit account. It emit some error as in below screenshot.
 ![image](https://img.esteem.ws/odaysaz3m2.jpg)
 ![image](https://img.esteem.ws/6qh3owuut2.jpg)
They had given the procedure video in YouTube to login with QR code scanning type although it emit some error.

**Comment by KorzunAV** [comment]
The message is issued if the Private Posting key does not pass validation. On the test account this problem could not be reproduced, so, possible causes - incorrect key entered (misprinting or scanner error). Try to enter the key manually. This should be exactly the Private Posting key, other keys will not be accepted. The private key usually starts with the characters 5K, 6K, 7K, 8K

**Comment by RanjithPVRP** [comment]
Ho ok, sir!  I will do it.  Thanks for the response :)
