### ISSUE TITLE
Missing photos

### ISSUE THREAD

**Issue by CanRau** [Chainers/steepshot-mobile#179]
Hey we started using steem/steepshot android couple of weeks ago as @gaiama most seems to work for us except on picture started to be missing in steepshot android app (on steemit it shows all correctly) which I commented [here](https://steemit.com/steepshot/@ashwinrajt/issues-with-steepshot-app-missing-photos-and-seeing-someoneelse-photos-in-my-gallery-250119a5e285d#@gaiama/re-vitality-re-ashwinrajt-issues-with-steepshot-app-missing-photos-and-seeing-someoneelse-photos-in-my-gallery-250119a5e285d-20180902t075228992z) now it's 8 missing images in total and we're a little confused cause we're trying to build a nice looking gallery (of course :D)
not to blame..just to inform and try to figure out what's going on and if they'll return eventually?

**Comment by KorzunAV** [comment]
Hi, our caching server was attacked, now all data is restored. Your content is stored in the cloud + IPFS and protected from such attacks, but it took some time to restore the quick data cache

**Comment by CanRau** [comment]
nasty attackers -.-
awesome we noticed the returned images yesterday just didn't had the time to comment
thank you 🥇 👍
