### ISSUE TITLE
green hand and fan

### ISSUE THREAD

**Issue by Upromise** [Chainers/steepshot-mobile#190]
Excuse me,Where are these files:Config.txt,DebugWif.txt,IntegrationModuleConfig.txt, or ask me What should be included in these documents,please.Thanks u

**Comment by KorzunAV** [comment]
Hi, ..\Steepshot.Android\Assets\ contain *.template files. Delete *.template extension to get Config.txt,DebugWif.txt,IntegrationModuleConfig.txt <= this files contains enviroment settings, so you need to fill you own keys
