### ISSUE TITLE
post__description-container not appearing when browsing with mosaic view

### ISSUE THREAD

**Issue by bycz6** [Chainers/steepshot-mobile#51]
# Description 
The post__description-container witch contains the user information not appearing when browsing with mosaic view.

This description (post__description-container) is from web app.

# Browser view 
![Screenshot_20171219-033025.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513654602/j4x0jwmpcr5d05mjrzvp.png)

# Open random post
![Screenshot_20171219-033039.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513654597/hfqpvve8mowhk0qnxdgo.png)

# Double click
![Screenshot_20171219-033046.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513654586/rrxspaemsgu8w3tfpdjd.png)

# Expected behavior > open like this when open a post
![Screenshot_20171219-221323.png](https://steemitimages.com/DQmSsbykmeeEcmNnxq1VYGQKhRys3jRcWppmUAs2YU8eKjk/Screenshot_20171219-221323.png)

# Hardware & Software
In my Huawei Honor 8 (FRD-L19)
With stock Android 7.0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@bycz/postdescription-container-not-appearing-when-browsing-with-mosaic-view">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
Hi! This feature already was added. Pul request https://github.com/Chainers/steepshot-mobile/pull/48/files. The view will be slightly different from your proposed. In particular, added ability to go to the next post by swipe.

**Comment by bycz6** [comment]
Nice

Cumprimentos / Best regards,
Rafael Mateus

Em 27/12/2017 5:43 a.m., "Korzun Alexander" <notifications@github.com>
escreveu:
