### ISSUE TITLE
Mobile App Bug: add account button 

### ISSUE THREAD

**Issue by yemmighto** [Chainers/steepshot-mobile#55]
Recently i notice the add account  button  on steepshot app is not working properly, when I was trying to add another account on steepshot using the app, it keep bring username doesn't exist,  I was surprised because  I just log the account  out

![IMG_20180101_020151_018.jpg](https://steemitimages.com/DQmeRfEqjFSCZ1d9Qr9CHumX3Ew68coumAjjYFbAh1GSoU7/IMG_20180101_020151_018.jpg)

below is the account  I was trying to add. it login first, as you can see in the video below. 

https://youtu.be/0H18XINWQks

Since the app can allow two more account on steepshot, so I decided to test it by adding another account  to it but I was surprised  what the result showed.  Video below 

https://youtu.be/qvC5qAu-RJ4

Without this bug  been fix,  adding of two or more account wont be possible.  

Mobile infinix hot 5
App version  0.1.0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@valchiz/mobile-app-bug-add-account-button">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
Hi, we support steem and golos. So you may add one account for steem and the second for golos. But you can`t add two steem or two golos accounts, sorry (not technical but historical reason). We will extend UI functionality in future...

**Comment by KorzunAV** [comment]
The text of the buttons is changed.
