### ISSUE TITLE
Upvoting or Commenting on a Deleted Post Results in Private Key Error

### ISSUE THREAD

**Issue by thewizardstudio** [Chainers/steepshot-mobile#60]
#### Expected Behavior
Attempting to Comment or Upvote a recently deleted Post from within Steepshot results in an error explaining that the post no longer exists.

#### Actual Behavior
Attempting to Comment or Upvote a recently deleted Post from within Steepshot results in an error explaining that your Private Key is not valid.

#### How to Reproduce
1. Launch Steepshot 0.1.1 (Build 60) on Android 8.1.0
2. Submit a Post 
3. Return to My Home and Refresh until the Post appears
4. Go to the Post in Steemit and Delete it
5. Return to Steepshot
6. Attempt to Upvote or Comment on the Post

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 0.1.1
---

#### Recording of the Bug
![DeletedCommentUpvote.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516919972/lcqebgu4jcqm53sshhhg.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/upvoting-or-commenting-on-a-deleted-post-results-in-private-key-error">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
Hi, thanks for your report. We have not yet added support for all messages from the blockchain, but it is in the near future. I plan to do this in next month.

**Comment by KorzunAV** [comment]
fixed https://github.com/Chainers/steepshot-mobile/commit/92162b2c438404da257f613d41e063e07163a57d
