### ISSUE TITLE
My Home Shows Incorrect Comment Counts if Made Outside of Steepshot

### ISSUE THREAD

**Issue by thewizardstudio** [Chainers/steepshot-mobile#61]
#### Expected Behavior
Comment counts on Posts in the My Home feed display the correct number of comments in the thread no matter what source they came from.

#### Actual Behavior
Comment counts on Posts in the My Home feed display incorrect values for the number of comments contained in the thread when they are made from outside of Steepshot.  Making a Comment in the thread from within Steepshot updates the values to the correct number.

#### How to Reproduce
1. Launch Steepshot 0.1.1 (Build 60) on Android 8.1.0
2. Submit a Post via Steepshot
3. Go to Steemit and Comment on the Post multiple times
4. Wait about 5 minutes
5. Return to Steepshot and Refresh the My Home page
6. View the Comment Count for the post from Step 2 (note it's incorrect)
7. Open the Post from Step 2
8. Make a Comment from Steepshot
9. Return to My Home and Refresh (note Comment Count is now correct)

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 0.1.1
---

#### Recording of the Bug
![CommentsFromSteemit.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516918327/uwlow7lgzgqyrqvlqchi.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/my-home-shows-incorrect-comment-counts-if-made-outside-of-steepshot">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mirrorrim** [comment]
Hello! Thanks for your feedback. Sorry for long answer. This issue is no longer actual - we fixed that on our backend.

**Comment by KorzunAV** [comment]
+ Sometimes the server needs more time to synchronize data from the blockchain and the database with the cache. It may take several minutes (usually up to 5 minutes)
