### ISSUE TITLE
Infinite Load Screen when Selecting Current User from Search

### ISSUE THREAD

**Issue by thewizardstudio** [Chainers/steepshot-mobile#62]
#### Expected Behavior
Searching for the Current User and selecting that profile takes the User to their My Profile page.

#### Actual Behavior
Searching for the Current User and selecting that profile takes the User to a Loading Screen which never ends.

#### How to Reproduce
1. Launch Steepshot 0.1.1 (Build 60) on Android 8.1.0
2. Tap the Compass Icon in the Lower Left
3. Tap the Search Field
4. Tap User
5. Search for the account you are actively using
6. Tap on the account when it appears

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 0.1.1
---

#### Recording of the Bug
![SearchActiveUser.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516920853/yetzxja0jaftqvfckpc3.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/infinite-load-screen-when-selecting-current-user-from-search">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
No longer reproduced
