### ISSUE TITLE
Photos are Altered When Rotated Multiple Times (In version 0.1.2.) 

### ISSUE THREAD

**Issue by richardoccas** [Chainers/steepshot-mobile#67]
<center>https://res.cloudinary.com/hpiynhbhq/image/upload/v1518242182/avtrpq5rwny9mp5w5qov.jpg</center>

### Expected behavior
<br>

When you create a post, once the image is loaded, you have a "rotate" button, with this option you can change the position of the image, that is, rotate it 90 ° as many times as you wish.

https://res.cloudinary.com/hpiynhbhq/image/upload/v1518239055/dinrb2pgnqir3ef8jccg.jpg

This doesn't represent a problem in the Steepshot web version, as can be seen in the following video.

<center>https://youtu.be/OakjsFGuXd0</center>

### Actual behavior

<br>
But this isn't the case with the web version of this platform, because when you click the "rotate" button several times, the image's resolution changes , affecting it.

You could think that this error is momentary and that it will be corrected when it is published, but this isn't so, the result obtained will be the publication of a distorted image.

### How to reproduce
<br>
#### Steps:

**#1:** Once inside the app, select the option to upload new photo (button with a camera symbol, located in the menu bar)

<center>https://res.cloudinary.com/hpiynhbhq/image/upload/v1518489170/sl0pei8altzrrl7vokyh.jpg</center>
<br>
**#2**: Now you can take the photo with the camera or choose it from your image album. In any of the options you can reproduce the bug.

<center>https://res.cloudinary.com/hpiynhbhq/image/upload/v1518489851/ntzaags1qvyjmg7llrda.jpg</center>
<br>
**#3**: Once the image has been chosen, you will rotate it several times (rotate button) and from 5 turns approximately the image will begin to distort.

<center>https://res.cloudinary.com/hpiynhbhq/image/upload/v1518490650/bwn7suefbekkvowfvhjw.jpg</center>
<br>
This bug was reproduce through a Blu cell phone, model R1 HD

* Operating system: Android 6.0
* RAM memory: 2GB
* App version: 0.1.2.

### Recording Of The Bug
<br>

##### - When loading the image:

<center>https://youtu.be/CBPfKxOPOxM</center>

<br>
<br>
##### - When the image is published:

  (Result: altered image)

<center>https://res.cloudinary.com/hpiynhbhq/image/upload/v1518240505/hwelvsrqycxikhjykma9.jpg</center>

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@richardoccas/steepshot-mobile-bug-report-image-setting">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
fixed
