### ISSUE TITLE
Steepshot Voting Power Bug

### ISSUE THREAD

**Issue by NileshBakshi** [Chainers/steepshot-mobile#69]
# Expected behavior
Steepshot displays the voting power of the person's account in profile

# Actual behavior
Steepshot shows the wrong voting power in your profile. I checked mine and it was about 7 units behind and for others the difference wasn't so drastic.

# How to reproduce
1. Login Steepshot click on your profile picture and check your voting power.
2. Compare voting power with other credible sources. I used www.steemd.com/@naysayer to check mine.

* App version : 0.1.2
* Operating system: Android OS 6.0.1

# Recording Of The Bug
https://youtu.be/tuzwzXWvDZg
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@naysayer/steepshot-voting-power-bug">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
"Voting power" on https: //steemd.com does not display the exact value. "steem" takes part of "Voting power" from accounts that are created through standard registration (not paid by the user), but does not display this fact.  This can be seen if you look at the "Voting power" of paid accounts, for example "steem"
