### ISSUE TITLE
App returns to enter posting key window each time i use the QR code scanner to scan the key barcode

### ISSUE THREAD

**Issue by djavalord** [Chainers/steepshot-mobile#75]
#### Expected behavior
i expect the app to log me in to my steepshot account if i scan my account posting key QR code

#### Actual behavior
i clicked on the scan the QR code, then scan my account posting key QR code, then the app returned me to the same page were i was requested to enter account posting key. i try it again and the same thing happened again.

#### How to reproduce
launch the app, select sign in with steen, then enter account name, click on next step then on the new window that opens, select  scan the QR code, then scan your account posting code from .

* Browser: steepshot
* Operating system: Android 5.5.1 Lollipop. infinix hot 3 LTE

#### Recording Of The Bug
https://youtu.be/-IywSKJtlIw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@javalord/app-returns-to-enter-posting-key-window-each-time-i-use-the-qr-code-scanner-to-scan-the-key-barcode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
Fixed. If the key does not match the account, then a message with an explanation should appear
