### ISSUE TITLE
Steepshot Bugs: camera buttons can not be pressed and app crashes

### ISSUE THREAD

**Issue by evisored** [Chainers/steepshot-mobile#80]
crash when going to take a picture

#### Expected behavior
I hope to shoot by pressing the button without any crashes.

#### Actual behavior
When I want to press the camera button we can not press the button and directly, I receive the message "steepshot is not responding"

#### How to reproduce
How to reproduce
This has happened since I will take a picture by pressing the camera button to post in Steepshot, which is done with the following steps:

Open the app
Tap the camera icon (new photo post)
The camera is open
can not press the image capture button
crash

 Operating system:
``` language
Xiaomi Mi Max 2

PLATFORM	: OS	Android 7.1.1 (Nougat)

Chipset              : Qualcomm MSM8953 Snapdragon 625

CPU	                : Octa-core 2.0 GHz Cortex-A53

GPU	                : Adreno 506
```

Recording Of The Bug
https://www.youtube.com/watch?v=2ATt0TBgmhE&feature=youtu.be

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@visored/steepshot-bugs-camera-buttons-can-not-be-pressed-and-app-crashes">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
Hi, thanks for the issue. The fix has been added (https://github.com/Chainers/steepshot-mobile/commit/ec37caf84a90d42144ca7e0410bb0e9200b7f992)
