### ISSUE TITLE
Steepshot Bugs: x button does not work and app crashes (app version 0.1.2 build number 68)

### ISSUE THREAD

**Issue by evisored** [Chainers/steepshot-mobile#82]
#### Expected behavior
I hope to be able to press the x key and return to the previous menu without crash.

#### Actual behavior
When I want to press the x button, I can not press the x button or it does not work and directly, I receive the message "steepshot not responding"

#### How to reproduce
Open the app Tap the camera icon (new photo post) The camera is open so you press the x button on the left corner and the x button does not work.

#### Operating system:

``` language
Xiaomi Mi Max 2

PLATFORM    : OS    Android 7.1.1 (Nougat)

Chipset              : Qualcomm MSM8953 Snapdragon 625

CPU                 : Octa-core 2.0 GHz Cortex-A53

GPU                 : Adreno 506
```

### APP VERSION
![Screenshot_2018-03-22-16-07-35-093_com.droid.steepshot.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521709995/dpppmvy2lsmnulcxwhzg.png)

#### Recording Of The Bug

https://youtu.be/Ospgmq-E7SM

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@visored/steepshot-bugs-x-button-does-not-work-and-app-crashes">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by KorzunAV** [comment]
fixed
