### ISSUE TITLE
Xamarin and Visual Studio version

### ISSUE THREAD

**Issue by phv1tr1996** [Chainers/steepshot-mobile#83]
Which xamarin and visual studio version are used for the mobile app?

**Comment by Nikitkao** [comment]
Visual Studio Community 2017 for Mac
Version 7.5 (build 1254)

Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

NuGet
Version: 4.3.1.4445

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Community)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.4.1.176 (Visual Studio Community)

Xamarin.iOS
Version: 11.10.1.177 (Visual Studio Community)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400
